### ISSUE TITLE
no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by mhadi4194** [GoogleCloudPlatform/retail-common-services#1]
Hello everyone,
I am facing issue creating a deployment on GKE cluster.
I used below deployment template provided in the repo
https://github.com/GoogleCloudPlatform/retail-common-services/blob/main/.cloudbuild-kubernetes/deployment.template.yaml

I get error message when I use deployment yaml with api version: extensions/v1beta1
```
no matches for kind "Deployment" in version "extensions/v1beta1"
```

After updating apiVersion to apps/v1, I used below yaml:

mydeployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spez-tailer-deployment
  namespace: nc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spez-tailer-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spez-tailer-deployment
        version: v1
    spec:
      containers:
      - args:
        - -Dspez.project_id=my-dev-project-id
        - -Dspez.auth.credentials=service-account.json
        - -Dspez.pubsub.topic=spez-ledger-topic
        - -Dspez.sink.instance=nc-event-sink-instance
        - -Dspez.sink.database=nc-event-sink-database
        - -Dspez.sink.table=aisleguideintm
        - -Dspez.sink.uuid_column=uuid
        - -Dspez.sink.timestamp_column=CommitTimestamp
        - -Dspez.lpts.instance=nc-event-sink-instance
        - -Dspez.lpts.database=spez-lpts-database
        - -Dspez.lpts.table=lpts
        - -Dspez.loglevel.default=WARNING
        - -Dspez.loglevel.com.google.spez.core.EventPublisher=WARNING
        - -Dspez.sink.poll_rate=30
        - -Dspez.pubsub.buffer_timeout=30
        - -Dspez.stackdriver.trace_sampling_rate=0.0000001
        # - -Dspez.project_id=spanner-event-exporter
        # - -Dspez.auth.credentials=credentials.json
        # - -Dspez.pubsub.topic=spez-ledger-topic
        # - -Dspez.sink.instance=spez-test-instance
        # - -Dspez.sink.database=spez-test-database
        # - -Dspez.sink.table=test
        # - -Dspez.sink.uuid_column=Id
        # - -Dspez.sink.timestamp_column=CommitTimestamp
        # - -Dspez.lpts.instance=spez-lpts-instance
        # - -Dspez.lpts.database=spez-lpts-database
        # - -Dspez.lpts.table=lpts
        # - -Dspez.loglevel.default=INFO
        # - -Dspez.loglevel.com.google.spez.core.EventPublisher=DEBUG
        image: gcr.io/my-dev-project-id/retail-common-services:latest
        imagePullPolicy: Always
        name: spez-tailer-deployment
        ports:
        - containerPort: 9010
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 2Gi
        volumeMounts:
        - mountPath: /var/run/secret/cloud.google.com
          name: service-account
          readOnly: true
      volumes:
      - name: service-account
        secret:
          secretName: service-account
```

deployment status:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/93664484/162854990-f7ade05d-3fdb-4a75-b813-aa9cc3e069e0.png">

error logs:
```
 -esa | -enablesystemassertions
 enable system assertions
Error
 -dsa | -disablesystemassertions
 -agentlib:<libname>[=<options>]
 load native agent library <libname>, e.g. -agentlib:jdwp
 see also -agentlib:jdwp=help
 -agentpath:<pathname>[=<options>]
 load native agent library by full pathname
 -javaagent:<jarpath>[=<options>]
 load Java programming language agent, see java.lang.instrument
 -splash:<imagepath>
 show splash screen with specified image
 HiDPI scaled images are automatically supported and used
 if available. The unscaled image filename, e.g. image.ext,
 should always be passed as the argument to the -splash option.
 The most appropriate scaled image provided will be picked up
 automatically.
 See the SplashScreen API documentation for more information
 @argument files
 one or more argument files containing options
 -disable-@files
 prevent further argument file expansion
 --enable-preview
 allow classes to depend on preview features of this release
To specify an argument for a long option, you can use --<name>=<value> or
--<name> <value>.
Usage: java [options] <mainclass> [args...]
 (to execute a class)
 or java [options] -jar <jarfile> [args...]
 (to execute a jar file)
 or java [options] -m <module>[/<mainclass>] [args...]
 java [options] --module <module>[/<mainclass>] [args...]
 (to execute the main class in a module)
```

system context:
my  GKE version: 1.21.9-gke.1002
private cluster (no external IP) with cloud NAT enabled
Organization has VPC service control enabled, build step with cloud build requires customization. I was able to build image with cloud build and push it to Google container registry.
dev environment: Mac OS Monterey 12.3
Google Cloud SDK 380.0.0
alpha 2022.04.01
beta 2022.04.01
bq 2.0.74
core 2022.04.01
gsutil 5.8
